/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

/**
 *
 * @author Dka
 */
public class ProvinciaForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form Provincia
     */
    public ProvinciaForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        ProyectorrhhAGCPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("ProyectorrhhAGCPU").createEntityManager();
        provinciaQuery = java.beans.Beans.isDesignTime() ? null : ProyectorrhhAGCPUEntityManager.createQuery("SELECT p FROM Provincia p");
        provinciaList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : provinciaQuery.getResultList();
        provinciaQuery1 = java.beans.Beans.isDesignTime() ? null : ProyectorrhhAGCPUEntityManager.createQuery("SELECT p FROM Provincia p");
        provinciaList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : provinciaQuery1.getResultList();
        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("proyectagcrrhh?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        provinciaQuery2 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Provincia p");
        provinciaList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : provinciaQuery2.getResultList();
        provinciaQuery3 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Provincia p");
        provinciaList3 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : provinciaQuery3.getResultList();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, provinciaList3, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idPROVINCIA}"));
        columnBinding.setColumnName("Id PROVINCIA");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idREGION}"));
        columnBinding.setColumnName("Id REGION");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nombreProvincia}"));
        columnBinding.setColumnName("Nombre Provincia");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);

        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager ProyectorrhhAGCPUEntityManager;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.util.List<Model.Provincia> provinciaList;
    private java.util.List<Model.Provincia> provinciaList1;
    private java.util.List<Model.Provincia> provinciaList2;
    private java.util.List<Model.Provincia> provinciaList3;
    private javax.persistence.Query provinciaQuery;
    private javax.persistence.Query provinciaQuery1;
    private javax.persistence.Query provinciaQuery2;
    private javax.persistence.Query provinciaQuery3;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
