/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

/**
 *
 * @author Dka
 */
public class ProvinciaForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form Provincia
     */
    public ProvinciaForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProyectorrhhAGCPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("ProyectorrhhAGCPU").createEntityManager();
        provinciaQuery = java.beans.Beans.isDesignTime() ? null : ProyectorrhhAGCPUEntityManager.createQuery("SELECT p FROM Provincia p");
        provinciaList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : provinciaQuery.getResultList();
        provinciaQuery1 = java.beans.Beans.isDesignTime() ? null : ProyectorrhhAGCPUEntityManager.createQuery("SELECT p FROM Provincia p");
        provinciaList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : provinciaQuery1.getResultList();
        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("proyectagcrrhh?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        provinciaQuery2 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Provincia p");
        provinciaList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : provinciaQuery2.getResultList();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 334, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager ProyectorrhhAGCPUEntityManager;
    private javax.persistence.EntityManager entityManager;
    private java.util.List<Model.Provincia> provinciaList;
    private java.util.List<Model.Provincia> provinciaList1;
    private java.util.List<Model.Provincia> provinciaList2;
    private javax.persistence.Query provinciaQuery;
    private javax.persistence.Query provinciaQuery1;
    private javax.persistence.Query provinciaQuery2;
    // End of variables declaration//GEN-END:variables
}
